### PR TITLE
fix completion signature formatting

### LINKED ISSUE #81: Custom completion info in the signature is missing after formatting
### Describe the bug

```nushell
def f1 [] { }
def f2 [foo: int@f1 = 1] { }
```

formats to

```nushell
def f1 [] { }
def f2 [foo: int = 1] { }
```

### PR DESCRIPTION
**Pull request by fdncred**
This PR fixes the issue in #81, the completion signature functionality. Before the formatter was stripping custom completion info `@f1` from function signatures like `def f2 [foo: int@f1 = 1]`. Had to bring in `Completion` in order to write the signature properly if `@<command_name>` is present.

closes #81

### CODE REVIEW

File: src/formatting.rs [hunk 1]
```diff
@@ -576,6 +576,15 @@ impl<'a> Formatter<'a> {
         }
     }
 
+    /// Write custom completion if present (e.g., @`completion_name`)
+    fn write_custom_completion(&mut self, completion: &Option<Completion>) {
+        if let Some(Completion::Command(decl_id)) = completion {
+            let decl = self.working_set.get_decl(*decl_id);
+            self.write("@");
+            self.write(decl.name());
```
Comment (blindFS) [inline src/formatting.rs]: Doe it work for quoted commands like `"complete foo"`?

File: src/formatting.rs [hunk 2]
```diff
@@ -631,7 +641,11 @@ impl<'a> Formatter<'a> {
             }
             if param.shape != SyntaxShape::Any {
                 self.write(": ");
-                self.write(&format!("{}", param.shape));
+                match &param.shape {
+                    SyntaxShape::Closure(Option::None) => self.write("closure"),
+                    _ => self.write(&format!("{}", param.shape)),
+                }
+                self.write_custom_completion(&param.completion);
```
Comment (blindFS) [inline src/formatting.rs]: Seems to be a common pattern, probably worth a `write_shape` helper in case there're more prettifying to do in the future.

And, some test cases for this matter?

File: src/formatting.rs (hunk 1 above)
Comment (blindFS) [reply src/formatting.rs]: And there's such syntax: `string@[a b c]`

Comment (blindFS) [reply src/formatting.rs]: Oh, one thing I forgot to mention is that `string@$foo` is allowed if `$foo` is a constant. It  will be expanded to string after formatting, presumably bad looking if the list gets long.


Best solution seems to be adding a new `Completion::Const(VarId)` entry to the enum.

Comment (fdncred) [reply src/formatting.rs]: Go for it. I'm kind of running out of gas with nufmt.
